### ISSUE TITLE
Wall of Shame Graphics

### ISSUE THREAD

**Issue by kevinreiss** [axapu/2015-code4lib-byob#2]
What image format will work best? PNG, Jpeg, does it matter?

Before:
- Pul Core - Before Fall 2014
- ILLiad 
- Aeon
- RBSC??
- Libguides - Before Fall 2014
- Music/Mendal
- Stokes/Eastasian
- Arch/Enginneering

After
- Pul Core
- ILLiad 
- Libguides
- Branch Homepage in PUL Core
- RBSC? 
- Versailles Project

**Comment by axamei** [comment]
PNG is preferable.
